apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-customers-argo-rollout
  labels:
    {{- include "customers_labels" . |indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      {{- include "customers_labels" . |indent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "customers_labels" . |indent 8 }}
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: {{ .Values.image.customers.registry }}/{{ .Values.image.customers.name }}:{{ .Values.image.customers.tag }}
          imagePullPolicy: Always
          name: customers
          ports:
            - containerPort: 3000
  strategy:
    canary:
      #      canaryService: customers-canary
      #      stableService: customers-stable
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Release.Name }}-customers-vs
            routes:
              - default
          destinationRule:
            name: {{ .Release.Name }}-customers-dr
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        - setWeight: 20
        - pause:
            duration: 1m
        - setWeight: 30
        - pause:
            duration: 1m
        - setWeight: 50
        - pause:
            duration: 1m
      analysis:
        templates:
          - templateName: success-rate
        startingStep: 2
        args:
          - name: service-name
            value: {{ .Release.Name }}-customers.{{ .Release.Namespace }}.svc.cluster.local
