---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-customers
  labels:
    {{- include "customers_labels" . |indent 4 }}
spec:
  selector:
    {{- include "customers_labels" . |indent 4 }}
  ports:
    - port: 80
      name: http
      targetPort: 3000
