apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-customers-dr
spec:
  host: {{ .Release.Name }}-customers
  subsets:
      - name: stable
        labels:
           {{- include "customers_labels"  . |indent 12 }}
      - name: canary
        labels:
          {{- include "customers_labels"  . |indent 12 }}
