apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-customers-vs
spec:
  hosts:
    - {{.Release.Name }}-customers
  http:
    - name: default
      route:
         - destination:
             host: {{ .Release.Name }}-customers
             subset: stable
           weight: 100
         - destination:
             host: {{ .Release.Name }}-customers
             subset: canary
           weight: 0 
