apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-customer-gateway
spec:
  selector:
     {{ tpl (toYaml .Values.istio.ingressGatewayLabels) .|indent 6 }}
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP
    hosts: 
      - {{ .Values.istio.webFrontendDNS }}
