apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-sealed-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    NAME: {{ .Values.secrets.NAME }} 
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-secret
      namespace: {{ .Release.Namespace }}
