apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-webfrontend-vs
spec:
  hosts:
    - {{ .Values.istio.webFrontendDNS }} 
  gateways:
    - {{ .Release.Name}}-customer-gateway
  http:
    - name: default
      match:
        - uri:
           prefix: /
      route:
         - destination:
             host: {{ .Release.Name }}-web-frontend
             subset: stable
           weight: 100
         - destination:
             host: {{ .Release.Name }}-web-frontend
             subset: canary
           weight: 0
