apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-info
  namespace: argocd
spec:
  ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    namespace: customers
    jqPathExpressions:
     - .spec.http[] |select(.name == "default")
  project: default
  source:
    chart: customer-info
    repoURL: https://shehbaz-pathan.github.io/customer-info/charts/chart/
    targetRevision: 0.1.1
    helm:
      releaseName: customer-info
      parameters:
        - name: image.webFrontend.tag
          value: web-frontend-c3ede4c3aba3b7e955c5803c5294d628465063e0
        - name: image.customers.tag
          value: customers-e9946189bf10f3d3c19cc1a7dcb71f182ce27c03
        - name: secrets.NAME
          value: AgCfcMAKzAHRQbwccHr/Zxg+ARqiOkkB2vuKjPEg6wgLn46JppDEZQhpklavQ5JVL8ZBdH/MGilLceq2dBpVPdMCc2Hb6Vfvio/VPllQrLMKERk+jHuvvIXaKIl3IOx8XvXqHA93qwLBS+lajrRTCXjzpFxzk/L9ZIYEjW3w1ve2tUjWO98D1LQE+V2J2zjoTGO1DorR/m8QbhkhpXr+PkbQFsYjSgU4BtRJ48ETpU7bFXugeaD5uxeRuleiiVfZ0DttomrGQLkgYB9F8yW7aJ6zM0LrcUq/Ph1V6wWWCySXA75TobQLQS2/uQOzv7+WIznjvTSObndbaFeOS2NqrB87/2oiG2AnoIaleekKIMeF+iOZV2/u9BkRvgOhtRjOjMB33oc8uuBzxeKS3PKH1wBw8h1Xu1NN6SH6RZcoOIfwZeNkqTeo3VRkhmsOo/xNF8XFcHeyl1fgQLZkZB0LvZboTG1XbUtAFOw26qymh2S/lqrAyTU+QOz/7M+nyePacKcKEQJvuP5SS7sQ9UjBRSK6lTjZJcRzLp9AyaeUXB4nOvkf56QArJNY1VBnxZJ6ZO8IK/DOvXds7SA+wtcl9ljQd3fZ383lxqWTNvsRIYx6wX0oUNimrvpjOAg29Y3Taw1pZFiWsNPaPxM++fjsIU2h+vUIIyOFo/1sb0Xa12Em2pcLFPy53neIJ2U7WE75njh0FHV0o4Hv 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cs-info
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
