apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-info-applications
  namespace: argocd
spec:
  generators: 
    - clusters:
         values:
            clusterName: '{{name}}'
  template:
     metadata:
       name: "customer-info-{{ name }}"
       namespace: argocd
     spec:
        ignoreDifferences:
         - group: networking.istio.io
           kind: VirtualService
           namespace: cs-info
           jqPathExpressions:
             - .spec.http[] |select(.name == "default")
        project: default
        source:
          chart: customer-info
          repoURL: https://shehbaz-pathan.github.io/customer-info/charts/chart/
          targetRevision: 0.1.1
          helm:
           releaseName: customer-info
           parameters:
            - name: image.webFrontend.tag
              value: web-frontend-c3ede4c3aba3b7e955c5803c5294d628465063e0
            - name: image.customers.tag
              value: customers-e9946189bf10f3d3c19cc1a7dcb71f182ce27c03 
            - name: istio.webFrontendDNS
              value: '{{values.clusterName}}-web-frontend.customer-details.com'
            - name: displayName
              value: '{{name}} cluster'
        destination:
          server: "{{ server }}"
          namespace: cs-info
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - RespectIgnoreDifferences=true
            - CreateNamespace=true
