apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-info-applications
  namespace: argocd
spec:
  template:
    spec:
      source:
        helm:
          parameters:
            - name: image.webFrontend.tag
              value: web-frontend-4bb403eae7867713c85d36c18df2b7c4af157827
            - name: image.customers.tag
              value: customers-fb9ebf8be977782254f4000a62806512f287158e
            - name: istio.webFrontendDNS
              value: '{{values.clusterName}}-web-frontend.customer-details.com'
            - name: displayName
              value: '{{name}} cluster'
