apiVersion: v1
entries:
  customer-info:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2022-11-28T18:27:07.77936494+05:30"
    description: A Helm chart customer-info webapp
    digest: 408570e99eb53ab957647ee7713284dfb6b463c46b7c51dccaab0a27c69e15f9
    name: customer-info
    type: application
    urls:
    - customer-info-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2022-11-28T18:27:07.779133977+05:30"
    description: A Helm chart customer-info webapp
    digest: e85ff0b605f8d8f055b539b3154384cdd41c56930e9fd9f87ab4caafccc96bb9
    name: customer-info
    type: application
    urls:
    - customer-info-0.1.0.tgz
    version: 0.1.0
generated: "2022-11-28T18:27:07.778833303+05:30"
