rolloutSpecs:
  replicaCount: 1
  revisionHistoryLimit: 5
  prometheusServiceAddress: http://prometheus.istio-system.svc.cluster.local:9090
image:
 customers:
   registry: docker.io/6255
   name: apps
   tag: customers-8d2e445218e6b3da3d9b076dfa2f731ebeed3848
 webFrontend:
   registry: docker.io/6255
   name: apps
   tag: web-frontend-761a829b51493fea23c89f68918af0d2bd074575
istio:
  webFrontendDNS: new-web-frontend.customer-details.com 
  ingressGatewayLabels:
    istio: ingressgateway
secrets:
   NAME: AgA/t3uo2VHK3fkYqk0x9iCwyGKzielnKgtYURIafRmsP8S3P78VV/gfv20aHBXqQ0OAIYTfJzbhMtEQIyAViv2TzH4aFIWPtDJmVLfW3go8b8n1OGRCZQ28lHlnVXsu0Upr+jzxtaeUpGfOvbyfHJFnM5MVsGlmURC14TfqdMxjpYiMJr4B94fZFSaOz8Az7pNnHLrZXhya/MRZ8k9+vBfpKCgXlL0RU9xkLiPJKadtMi1OgkT9opJZjvBexJdx5SKUBwcQfMBc62Jng0fk3KeysxuOjXpLhORrP0xbdRQj7ZBeWX6iSExvY51biMTuDO9/QV7STQHhwZ7s0Wd7aM1FDOhR1rCLLQhDkweuoE4pq55ZHpcPabHuBfHx94PjLgGpKE/n1Sy+w4Jzl/gqnELnzU9qCkxCmzXQJu17iucd8Fzgpry9GPi0yptvntBs8io80v/JhcaQ1ZZ0sXod/MArJdQLJcmz6UyMDvHZqOeZaoOGFeA5w83kwuDdM10iczbUG8jFC9vdMk0xp1wNsdDKQPH2CF79EuvLVYi95UU02Q2pVDIhwCiNBxGCvp8JTWXQZpFfIp7V+NrItWBU3hd7pZ1qftgxaxuLKK5BCOlnObOusMXBcHzbTDeiM3UopYCbnL2+A9D0Ol2siR+ZOR1PPIPLZ8/ZHnTz2LoJNraRcCAI4rdzj84mrh5cwCUMipp3wwtI7FBx
